config/routes.rb
Catalogador::Application.routes.draw do

   get "items/list"
   post "items/list"

  resources :items do
    resources :comments
   end

   resources :welcome

   root 'welcome#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :item
end

app/models/cover.rb
class Cover < ActiveRecord::Base
	belongs_to :item
	has_attached_file :cover

	validates_attachment :cover, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }

	before_post_process :process_only_covers

	def process_only_covers
     %w(image/jpeg, image/png,image/gif,image/pjpeg, image/x-png).include?(cover_content_type)
    end


end

app/models/item.rb
class Item < ActiveRecord::Base

	has_many :comments, dependent: :destroy #se hace esta modificacion para que se borre en cascada los comentarios si un juego es borrado
	validates :name, presence: true, length: {minimum: 2}

	has_many :covers, dependent: :destroy

	def attachments_array=(array)
		array.each do |file|
			covers.build(:cover => file)
		end
	end


	
	#has_many :comments
	#No guarda en la base de datos si el largo es menor que 5
	#validates :description, presence: true, length: {minimum: 5}

	#def self.search(search, page)
	#	if search
    #		#find(:all, :conditions => ['name LIKE ? OR system = ?', "%#{search}%", "%#{search_combo}%"])
    #		find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  	#	else
    #		find(:all)
  	#	end
	#end

	def self.search(search, page, fav, search_combo)
		conditions = ['system = ?', "#{search_combo}"]
 		#conditions = nil

 		if search_combo.blank?
 			conditions = ['system like ?', "1"] #Por defecto busca los de PSX
 		end	

  		unless search.blank?
    		##conditions = ['name like ? AND system = ?', "%#{search}%", "#{search_combo}"]
    		conditions = ['name like ? AND system = ?', "%#{search}%", "#{search_combo}"]
  		end

  		unless fav.blank?
    		conditions = ['favorite = ? AND system = ?', 1, "#{search_combo}"]
  		end


  		paginate :per_page => 12, :page => page, :conditions => conditions, :order => 'name'
	end
end

app/models/system.rb
class System < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
    	@item = Item.find(params[:item_id])
    	@comment = @item.comments.create(params[:comment].permit(:mycomment))
    	redirect_to item_path(@item)
	end

	def destroy
    	@item = Item.find(params[:item_id])
    	@comment = @item.comments.find(params[:id])
    	@comment.destroy
    	redirect_to item_path(@item)
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def new
		@item = Item.new #para que no de NIL en las validaciones del formulario
	end

	#def index
	#	if params[:search]
	#  		@items =  Item.find(:all, :conditions => ['name LIKE ?', "%#{params[:search]}%"])
	#  	else
  	#			@items = Item.find(:all)
  	#	end
	#end

	def index
		#@items = Item.order("name").page(params[:page]).per_page(15)
		#@items = Item.search(params[:search]).page(params[:page])
		@items = Item.search(params[:search], params[:page], params[:fav], params[:search_combo])
		#@items = Item.search({:search => params[:search], :search_combo => params[:search_combo]})
		@systems = System.find(:all)
	end

	def list
		#<%= form_tag(:controller => "items", :action => "list", :method => "get") do %>
		@items = Item.search(params[:search], params[:page], params[:fav], params[:search_combo])
		@systems = System.find(:all)
	end

	#accion
	def create
		#render text: params[:ps1].inspect
		@item = Item.new(item_params)

		#@ps1.save puede quedar de esta forma tambien
		# si graba
		if @item.save
			redirect_to @item
		else
			render 'new'
		end		
  	end

  	#mostrar
  	#es importante el orden, private está tomando control sobre todo lo que está abajo de el.
	def show
  		@item = Item.find(params[:id])
	end

	#mostrar
	def edit
		@item = Item.find(params[:id])
	end

	#accion
	def update
		@item = Item.find(params[:id])

		if @item.update(params[:item].permit(:name, :dvd, :dvd2, :filename, :system, :recorded, :copies, :favorite, :cover, :attachments_array => []))
			redirect_to @item
		else
			render 'edit'
		end	
	end	

	#accion
	def destroy
  		@item = Item.find(params[:id])
  		@item.destroy
 
  		redirect_to items_path
	end

  	private
  		def item_params
  			params.require(:item).permit(:name, :dvd, :dvd2, :filename, :system, :recorded, :copies, :favorite, :cover, :attachments_array => [])
  		end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.mycomment %>
</p>
<p>
	<%= link_to 'Borrar comentario', [comment.item, comment],
               method: :delete,
               data: { confirm: 'Estas seguro?' }, :class => "btn btn-primary" %>
 </p>

app/views/comments/_form.html.erb
<%= stylesheet_link_tag "bootstrap" %>
<%= form_for([@item, @item.comments.build]) do |f| %>
  <p>
    <%= f.label "Añadir un comentario" %><br />
    <%= f.text_area :mycomment, :size => "45x5" %>
    <%= f.submit "Guardar" ,:class => "btn btn-primary"%>
  </p>
<% end %>

app/views/items/_form.html.erb
<%= form_for @item , :html => { :multipart => true } do |f| %>

	<% if @item.errors.any? %>
	<div id="errorExplanation">
	<h2><%= pluralize(@item.errors.count, "error") %> hicieron que este formulario no se guardara:</h2>
	<ul>
	<% @item.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
	</ul>
	</div>
	<% end %>

	<div class="row" style="max-width: 800px;">
		<div class="col-md-3 col-sm-3"><p><label>Nombre</label> </br><%= f.text_field :name%></p> </div>
	    
	   	<div class="col-md-3 col-sm-2">
	    		<label>Plataforma</label></br>
	    		<%= f.collection_select :system, System.all, :id, :sysname, :prompt => "Seleccione el sistema", :class => "input-large" %>
	    </div>
	</div>
	<div class="row" style="max-width: 800px;">   
		<div class="col-md-3 col-sm-3"><p> <label>Favorito</label></br><%= f.check_box :favorite, :class => "checkbox"%> </p></div>
	</div>
	<div class="row" style="max-width: 800px;">
		<div class="col-md-5 col-sm-6">
			<label>Carátulas (Seleccione 1 a 3 imágenes)</label>
			<%= f.file_field :attachments_array, :multiple => :true %> 
		</div>	
	</div>
	<div class="row" style="max-width: 800px;">
		<div class="col-md-11 col-sm-11" style="text-align: right;">
		 	<%= f.submit "Guardar", :class=>"btn btn-primary" %>
			<%= link_to 'Volver', items_path, :class => "btn btn-success" %>
		</div>
	</div>
<% end %>

app/views/items/edit.html.erb
<fieldset>
	<legend>Editar Item</legend>
	<%= render 'form' %>
 </fieldset> 

app/views/items/index.html.erb
  <%= form_tag items_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= select_tag :search_combo,
            options_from_collection_for_select(@systems, "id", "sysname", params[:search_combo])%>
      Favorito <%= check_box_tag :fav, params[:fav] %>
      <%= submit_tag "Buscar", :name => nil, :class => "btn btn-info"%>
    </p>
 
  <a href="/items/new" class="btn btn-success">Nuevo</a>

  <table class="table table-hover">
  <tr>
    <th>Nombre</th>
    <th>Plataforma</th>
    <th></th>
  </tr>
   
  <div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @items %>
    </div>
    <%= will_paginate @items %>
  </div>

  <% @items.each do |item| %>

    <tr>
      <td><%= item.name %></td>
      <td><%= item.system %></td>
      <td style="width:90px">
        <div class="btn-group">
          <%= link_to 'S', item_path(item), :class => "btn btn-info" %> <!-- en el tutorial estaba malo, habia que pasarle item -->
          <%= link_to 'E', edit_item_path(item), :class => "btn btn-warning" %>
          <!-- <%= link_to 'D', item_path(item), method: :delete, data: { confirm: 'Estas seguro?' }, :class => "btn btn-danger"%> -->
        </div>
      </td>
    </tr>
  <% end %>


</table>

  <div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @items %>
    </div>
    <%= will_paginate @items %>
  </div>

   <% end %>


<!--<%= link_to 'Volver', controller: "items"%> -->
 <!--<%= link_to 'Nuevo Item', new_item_path %> -->

app/views/items/list.html.erb
<%= form_tag request.path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= select_tag :search_combo,
            options_from_collection_for_select(@systems, "id", "sysname", params[:search_combo])%>
      Favorito <%= check_box_tag :fav, params[:fav] %>
      <%= submit_tag "Buscar", :name => nil, :class => "btn btn-info"%>
    </p>

  <a href="/items/new" class="btn btn-success">Nuevo</a>

  <div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @items %>
    </div>
    <%= will_paginate @items %>
  </div>

<table style="min-width:200px;">
  
  <% @items.each do |item| %>
  <tr style="max-width:1000px;" >
    <td>
      <div style="min-height:35px;"><label><%= item.name %></label></div>
      <% if item.covers.first %>
        <div style="max-height:350px;">
          <%= link_to item_path(item) do %> 
          <%= image_tag item.covers.first.try(:cover).to_s, :width => "330px", :class => "img-rounded" %>
          <% end %>

        </div>
      <% else %>
          <div style="man-height:550px;"><%= image_tag "sincaratula.gif", :width => "330px" , :class => "img-rounded" %></div>
      <% end %>
      <br />
        </br>
        </br>
        </br>
        </br>
        </br>
        </br>

    </td>
  </tr>

  <% end %>

</div>

</table>


  <div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @items %>
    </div>
    <%= will_paginate @items %>
  </div>

  <% end %>

app/views/items/new.html.erb
<fieldset>
	<legend>Nuevo Item</legend>
	<%= render 'form' %>
</fieldset>

app/views/items/show.html.erb
<div class="row" style="max-width: 1000px;">
  <div class="col-md-7 col-sm-8">
    <% if @item.covers.first %>
        <%= link_to @item.covers.first.cover.url, id: "cover1", :class => "imagen-pequena" do %>
        <%= image_tag @item.covers.first.cover.url, :width=> "300px", :class => "img-rounded" %>
    <% end %>
    <% else %>
      <%= image_tag "sincaratula.gif", :width=> "300px", :class => "img-rounded" %>
    <% end %>
  </div>
</br>
  <div class="col-md-5 col-sm-8">
    <div><h3><%= @item.name %></h3></div>
      <p>
          <strong>Plataforma:</strong>
          <%= @item.system %>
        </div>  
      </p>
  </div>   

  <div class="col-md-5 col-sm-8">
      <%= render @item.comments %> <!--  renderiza de la carpeta comments el parcial _comment-->
      <%= render "comments/form" %> <!--  renderiza de la carpeta comments el parcial _form-->
  </div>
 </div>

<div class="row" style="max-width: 1000px;">

</br>
</br>
  <div class="col-md-4 col-sm-8">
  <p>  
   <% if @item.covers.second %>
        <%= link_to @item.covers.second.cover.url, id: "cover1", :class => "imagen-pequena" do %>
        <%= image_tag @item.covers.second.cover.url, :width=> "300px", :class => "img-rounded" %>
    <% end %>
    <% else %>
        <%= image_tag "sincaratula.gif", :width => "300px", :class => "img-rounded" %>
    <% end %>
  </p>  
  </div>


  <div class="col-md-4 col-sm-8">
  <p>
    <% if @item.covers.third %>
        <%= link_to @item.covers.third.cover.url, id: "cover1", :class => "imagen-pequena" do %>
        <%= image_tag @item.covers.third.cover.url, :width=> "300px",:class => "img-rounded" %>
    <% end %>
    <% else %>
        <%= image_tag "sincaratula.gif", :width=> "300px", :class => "img-rounded" %>
    <% end %>
  </p>  
  </div>

  <div class="col-md-4 col-sm-8">
  <p>  
    <% if @item.covers.fourth %>
          <%= link_to @item.covers.fourth.cover.url, id: "cover1", :class => "imagen-pequena" do %>
          <%= image_tag @item.covers.fourth.cover.url, :width=> "300px", :class => "img-rounded" %>
    <% end %>
    <% else %>
          <%= image_tag "sincaratula.gif", :width=> "300px", :class => "img-rounded" %>
    <% end %>
  </p>  
  </div>

  <div class="col-md-12 col-sm-5" style="text-align: right;">
  </br>
    <%= link_to_function "Volver", "history.back()", :class => "btn btn-sucess"%>
    <%= link_to 'Editar', edit_item_path(@item), :class => "btn btn-warning" %>
  </div>

</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Catalogador</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'jquery-2.1.0.min.js', 'application' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Catalogador Ruby on Rails", "#", :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><%= link_to "Lista Items", controller: "items" %></li>
          <li><%= link_to "Lista Galeria", controller: "items", action: "list" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag "bootstrap" %>